import Foundation

// MARK: - Languages

enum AppLanguage: String, CaseIterable, Identifiable {
    case en, es, pt, fr, de, it, ja, zh, ko
    var id: String { rawValue }

    var nativeName: String {
        switch self {
        case .en: return "English"
        case .es: return "Español"
        case .pt: return "Português"
        case .fr: return "Français"
        case .de: return "Deutsch"
        case .it: return "Italiano"
        case .ja: return "日本語"
        case .zh: return "中文"
        case .ko: return "한국어"
        }
    }

    var flag: String {
        switch self {
        case .en: return "🇺🇸"
        case .es: return "🇪🇸"
        case .pt: return "🇧🇷"
        case .fr: return "🇫🇷"
        case .de: return "🇩🇪"
        case .it: return "🇮🇹"
        case .ja: return "🇯🇵"
        case .zh: return "🇨🇳"
        case .ko: return "🇰🇷"
        }
    }

    static var systemDefault: AppLanguage {
        let preferred = (Locale.preferredLanguages.first ?? "en")
            .lowercased()
        let code = String(preferred.prefix(2))
        return AppLanguage(rawValue: code) ?? .en
    }
}

// MARK: - String keys

enum LocKey: String {
    case appSubtitle

    case statusPaused, statusNoDisplaysShort, statusManualRest, statusScheduled
    case statusMediaPaused, statusIdleBlackout
    case statusActiveOne, statusActiveMany, statusIdle

    case subPaused, subNoDisplays, subManualRest, subScheduled
    case subMediaPaused, subIdleBlackout, subActive

    case sectionDisplays, sectionAppearance, sectionCare, sectionSchedule, sectionLanguage

    case noDisplaysDetected, badgeExternal, displayBuiltin, displayExternal
    case displayProtected, displayNotProtected

    case style, styleBlack, styleWhite, styleBlur
    case opacity, fadeSpeed, fadeInstant, leaveDelay, leaveNone, previewLabel

    case carePauseMediaTitle, carePauseMediaSubtitle
    case carePixelShiftTitle, carePixelShiftSubtitle
    case careBlackoutIdleTitle, careBlackoutIdleSubtitle
    case idleThreshold
    case minute_1, minutes_2, minutes_5, minutes_10, minutes_30
    case wakeDisplays, restDisplaysNow

    case scheduleTitle, scheduleSubtitle, scheduleFrom, scheduleTo

    case totalProtected, unitHourMin, unitMin, unitSec

    case menuPause, menuResume, menuPreferences, menuQuit

    // Hibernation / battery saver
    case statusHibernating
    case subHibernateNoExternal, subHibernateBatterySaver, subHibernateLowBattery
    case sectionPower
    case careBatterySaverTitle, careBatterySaverSubtitle
    case careAutoBatterySaverTitle, careAutoBatterySaverSubtitle
    case powerNoExternalNote

    // Launch at login
    case careLaunchAtLoginTitle, careLaunchAtLoginSubtitle

    // Sticky footer
    case applyAndClose
}

// MARK: - Translations

private let strings: [AppLanguage: [LocKey: String]] = [

.en: [
    .appSubtitle: "Burn-in protection for your monitor",
    .statusPaused: "Paused",
    .statusNoDisplaysShort: "No displays selected for protection",
    .statusManualRest: "Resting displays",
    .statusScheduled: "Resting on schedule",
    .statusMediaPaused: "Paused — media is playing",
    .statusIdleBlackout: "Blackout — system is idle",
    .statusActiveOne: "Active — protecting 1 display",
    .statusActiveMany: "Active — protecting %d displays",
    .statusIdle: "Idle — no displays selected for protection",
    .subPaused: "Display Flow is off",
    .subNoDisplays: "Toggle a display below to start",
    .subManualRest: "Click Wake Displays to resume",
    .subScheduled: "Auto-rest window is active",
    .subMediaPaused: "Will resume when playback stops",
    .subIdleBlackout: "Wakes on any input",
    .subActive: "Move your cursor between screens",
    .sectionDisplays: "Displays",
    .sectionAppearance: "Appearance",
    .sectionCare: "Care",
    .sectionSchedule: "Schedule",
    .sectionLanguage: "Language",
    .noDisplaysDetected: "No displays detected.",
    .badgeExternal: "EXTERNAL",
    .displayBuiltin: "Built-in",
    .displayExternal: "External",
    .displayProtected: "Protected",
    .displayNotProtected: "Not protected",
    .style: "Style",
    .styleBlack: "Black",
    .styleWhite: "White",
    .styleBlur: "Blur",
    .opacity: "Opacity",
    .fadeSpeed: "Fade speed",
    .fadeInstant: "Instant",
    .leaveDelay: "Leave delay",
    .leaveNone: "None",
    .previewLabel: "Your screen",
    .carePauseMediaTitle: "Pause while a video is on screen",
    .carePauseMediaSubtitle: "Full-screen, picture-in-picture, or in a tab — any visible video. Audio-only apps (music, voice calls) won't pause the dimming.",
    .carePixelShiftTitle: "Pixel shift",
    .carePixelShiftSubtitle: "Subtly drifts the overlay ±1 pixel every minute so the menu-bar cover doesn't always sit on the same physical pixels.",
    .careBlackoutIdleTitle: "Blackout protected displays when idle",
    .careBlackoutIdleSubtitle: "After a period of no input, fully cover protected displays.",
    .idleThreshold: "Idle threshold",
    .minute_1: "1 minute",
    .minutes_2: "2 minutes",
    .minutes_5: "5 minutes",
    .minutes_10: "10 minutes",
    .minutes_30: "30 minutes",
    .wakeDisplays: "Wake Displays",
    .restDisplaysNow: "Rest Displays Now",
    .scheduleTitle: "Auto-rest on schedule",
    .scheduleSubtitle: "Force-rest protected displays during set hours.",
    .scheduleFrom: "From",
    .scheduleTo: "to",
    .totalProtected: "Total time protected: %@",
    .unitHourMin: "%dh %dm",
    .unitMin: "%dm",
    .unitSec: "%ds",
    .menuPause: "Pause Display Flow",
    .menuResume: "Resume Display Flow",
    .menuPreferences: "Preferences…",
    .menuQuit: "Quit Display Flow",
    .statusHibernating: "Hibernating",
    .subHibernateNoExternal: "No external display connected",
    .subHibernateBatterySaver: "Battery saver mode is on",
    .subHibernateLowBattery: "Battery is below 50%",
    .sectionPower: "Power",
    .careBatterySaverTitle: "Battery saver mode",
    .careBatterySaverSubtitle: "Pause everything and free all resources.",
    .careAutoBatterySaverTitle: "Auto-pause below 50% battery",
    .careAutoBatterySaverSubtitle: "Stop monitoring when on battery and getting low.",
    .powerNoExternalNote: "Always pauses when no external display is connected.",
    .careLaunchAtLoginTitle: "Open at login",
    .careLaunchAtLoginSubtitle: "Start Display Flow automatically when you sign in to your Mac.",
    .applyAndClose: "Apply",
],

.es: [
    .appSubtitle: "Protección anti-quemado para tu monitor",
    .statusPaused: "En pausa",
    .statusNoDisplaysShort: "Ninguna pantalla seleccionada",
    .statusManualRest: "Pantallas en descanso",
    .statusScheduled: "Descansando según horario",
    .statusMediaPaused: "En pausa — hay un video reproduciéndose",
    .statusIdleBlackout: "Apagado — sistema inactivo",
    .statusActiveOne: "Activo — protegiendo 1 pantalla",
    .statusActiveMany: "Activo — protegiendo %d pantallas",
    .statusIdle: "Inactivo — ninguna pantalla seleccionada",
    .subPaused: "Display Flow está desactivado",
    .subNoDisplays: "Activa una pantalla abajo para empezar",
    .subManualRest: "Haz clic en Despertar pantallas para reanudar",
    .subScheduled: "Horario de descanso automático activo",
    .subMediaPaused: "Volverá cuando se detenga la reproducción",
    .subIdleBlackout: "Se despierta con cualquier entrada",
    .subActive: "Mueve el cursor entre pantallas",
    .sectionDisplays: "Pantallas",
    .sectionAppearance: "Apariencia",
    .sectionCare: "Cuidado",
    .sectionSchedule: "Horario",
    .sectionLanguage: "Idioma",
    .noDisplaysDetected: "Ninguna pantalla detectada.",
    .badgeExternal: "EXTERNA",
    .displayBuiltin: "Integrada",
    .displayExternal: "Externa",
    .displayProtected: "Protegida",
    .displayNotProtected: "No protegida",
    .style: "Estilo",
    .styleBlack: "Negro",
    .styleWhite: "Blanco",
    .styleBlur: "Borroso",
    .opacity: "Opacidad",
    .fadeSpeed: "Velocidad de fundido",
    .fadeInstant: "Instantáneo",
    .leaveDelay: "Retraso al salir",
    .leaveNone: "Ninguno",
    .previewLabel: "Tu pantalla",
    .carePauseMediaTitle: "Pausar cuando hay un video en pantalla",
    .carePauseMediaSubtitle: "Pantalla completa, picture-in-picture o en una pestaña — cualquier video visible. Las apps de solo audio (música, llamadas de voz) no pausan el oscurecido.",
    .carePixelShiftTitle: "Desplazamiento de píxeles",
    .carePixelShiftSubtitle: "Desplaza la cubierta ±1 píxel cada minuto para que el cubre-menú no quede siempre sobre los mismos píxeles físicos.",
    .careBlackoutIdleTitle: "Apagar pantallas protegidas al estar inactivo",
    .careBlackoutIdleSubtitle: "Tras un periodo sin entrada, cubrir totalmente las pantallas protegidas.",
    .idleThreshold: "Umbral de inactividad",
    .minute_1: "1 minuto",
    .minutes_2: "2 minutos",
    .minutes_5: "5 minutos",
    .minutes_10: "10 minutos",
    .minutes_30: "30 minutos",
    .wakeDisplays: "Despertar pantallas",
    .restDisplaysNow: "Descansar pantallas ahora",
    .scheduleTitle: "Descanso automático por horario",
    .scheduleSubtitle: "Forzar descanso de pantallas protegidas durante las horas configuradas.",
    .scheduleFrom: "Desde",
    .scheduleTo: "hasta",
    .totalProtected: "Tiempo total protegido: %@",
    .unitHourMin: "%dh %dm",
    .unitMin: "%dm",
    .unitSec: "%ds",
    .menuPause: "Pausar Display Flow",
    .menuResume: "Reanudar Display Flow",
    .menuPreferences: "Preferencias…",
    .menuQuit: "Salir de Display Flow",
    .statusHibernating: "Hibernando",
    .subHibernateNoExternal: "No hay pantalla externa conectada",
    .subHibernateBatterySaver: "Modo ahorro de batería activo",
    .subHibernateLowBattery: "Batería por debajo del 50%",
    .sectionPower: "Energía",
    .careBatterySaverTitle: "Modo ahorro de batería",
    .careBatterySaverSubtitle: "Pausa todo y libera los recursos del sistema.",
    .careAutoBatterySaverTitle: "Pausar automáticamente bajo 50%",
    .careAutoBatterySaverSubtitle: "Detiene el monitoreo cuando estás con batería y está bajando.",
    .powerNoExternalNote: "Siempre pausa cuando no hay pantalla externa conectada.",
    .careLaunchAtLoginTitle: "Abrir al iniciar sesión",
    .careLaunchAtLoginSubtitle: "Inicia Display Flow automáticamente cuando enciendas tu Mac.",
    .applyAndClose: "Aplicar",
],

.pt: [
    .appSubtitle: "Proteção contra burn-in para seu monitor",
    .statusPaused: "Pausado",
    .statusNoDisplaysShort: "Nenhuma tela selecionada",
    .statusManualRest: "Telas em descanso",
    .statusScheduled: "Descansando conforme programação",
    .statusMediaPaused: "Pausado — há um vídeo em reprodução",
    .statusIdleBlackout: "Desligado — sistema ocioso",
    .statusActiveOne: "Ativo — protegendo 1 tela",
    .statusActiveMany: "Ativo — protegendo %d telas",
    .statusIdle: "Ocioso — nenhuma tela selecionada",
    .subPaused: "Display Flow está desligado",
    .subNoDisplays: "Ative uma tela abaixo para começar",
    .subManualRest: "Clique em Acordar telas para retomar",
    .subScheduled: "Janela de descanso automático ativa",
    .subMediaPaused: "Voltará quando a reprodução parar",
    .subIdleBlackout: "Acorda com qualquer entrada",
    .subActive: "Mova o cursor entre as telas",
    .sectionDisplays: "Telas",
    .sectionAppearance: "Aparência",
    .sectionCare: "Cuidado",
    .sectionSchedule: "Programação",
    .sectionLanguage: "Idioma",
    .noDisplaysDetected: "Nenhuma tela detectada.",
    .badgeExternal: "EXTERNA",
    .displayBuiltin: "Integrada",
    .displayExternal: "Externa",
    .displayProtected: "Protegida",
    .displayNotProtected: "Não protegida",
    .style: "Estilo",
    .styleBlack: "Preto",
    .styleWhite: "Branco",
    .styleBlur: "Desfocado",
    .opacity: "Opacidade",
    .fadeSpeed: "Velocidade de fade",
    .fadeInstant: "Instantâneo",
    .leaveDelay: "Atraso ao sair",
    .leaveNone: "Nenhum",
    .previewLabel: "Sua tela",
    .carePauseMediaTitle: "Pausar quando há vídeo na tela",
    .carePauseMediaSubtitle: "Tela cheia, picture-in-picture ou em uma aba — qualquer vídeo visível. Apps de apenas áudio (música, chamadas de voz) não pausam o escurecimento.",
    .carePixelShiftTitle: "Deslocamento de pixels",
    .carePixelShiftSubtitle: "Desloca a cobertura ±1 pixel a cada minuto para que a barra de menu não fique sempre sobre os mesmos pixels físicos.",
    .careBlackoutIdleTitle: "Apagar telas protegidas quando ocioso",
    .careBlackoutIdleSubtitle: "Após um período sem entrada, cobrir totalmente as telas protegidas.",
    .idleThreshold: "Limite de ociosidade",
    .minute_1: "1 minuto",
    .minutes_2: "2 minutos",
    .minutes_5: "5 minutos",
    .minutes_10: "10 minutos",
    .minutes_30: "30 minutos",
    .wakeDisplays: "Acordar telas",
    .restDisplaysNow: "Descansar telas agora",
    .scheduleTitle: "Descanso automático programado",
    .scheduleSubtitle: "Forçar descanso das telas protegidas durante as horas configuradas.",
    .scheduleFrom: "De",
    .scheduleTo: "até",
    .totalProtected: "Tempo total protegido: %@",
    .unitHourMin: "%dh %dm",
    .unitMin: "%dm",
    .unitSec: "%ds",
    .menuPause: "Pausar Display Flow",
    .menuResume: "Retomar Display Flow",
    .menuPreferences: "Preferências…",
    .menuQuit: "Sair do Display Flow",
    .statusHibernating: "Hibernando",
    .subHibernateNoExternal: "Nenhuma tela externa conectada",
    .subHibernateBatterySaver: "Modo economia de bateria ativo",
    .subHibernateLowBattery: "Bateria abaixo de 50%",
    .sectionPower: "Energia",
    .careBatterySaverTitle: "Modo economia de bateria",
    .careBatterySaverSubtitle: "Pausa tudo e libera todos os recursos.",
    .careAutoBatterySaverTitle: "Pausar automaticamente abaixo de 50%",
    .careAutoBatterySaverSubtitle: "Para o monitoramento quando estiver na bateria e ela estiver baixa.",
    .powerNoExternalNote: "Sempre pausa quando não há tela externa conectada.",
    .careLaunchAtLoginTitle: "Abrir ao iniciar sessão",
    .careLaunchAtLoginSubtitle: "Inicia o Display Flow automaticamente quando você liga o Mac.",
    .applyAndClose: "Aplicar",
],

.fr: [
    .appSubtitle: "Protection contre l'effet rémanent pour votre moniteur",
    .statusPaused: "En pause",
    .statusNoDisplaysShort: "Aucun écran sélectionné",
    .statusManualRest: "Écrans en repos",
    .statusScheduled: "Repos selon l'horaire",
    .statusMediaPaused: "En pause — une vidéo est en cours",
    .statusIdleBlackout: "Écran noir — système inactif",
    .statusActiveOne: "Actif — protection de 1 écran",
    .statusActiveMany: "Actif — protection de %d écrans",
    .statusIdle: "Inactif — aucun écran sélectionné",
    .subPaused: "Display Flow est désactivé",
    .subNoDisplays: "Activez un écran ci-dessous pour commencer",
    .subManualRest: "Cliquez sur Réveiller les écrans pour reprendre",
    .subScheduled: "La fenêtre de repos automatique est active",
    .subMediaPaused: "Reprendra à l'arrêt de la lecture",
    .subIdleBlackout: "Se réveille à toute saisie",
    .subActive: "Déplacez votre curseur entre les écrans",
    .sectionDisplays: "Écrans",
    .sectionAppearance: "Apparence",
    .sectionCare: "Protection",
    .sectionSchedule: "Horaire",
    .sectionLanguage: "Langue",
    .noDisplaysDetected: "Aucun écran détecté.",
    .badgeExternal: "EXTERNE",
    .displayBuiltin: "Intégré",
    .displayExternal: "Externe",
    .displayProtected: "Protégé",
    .displayNotProtected: "Non protégé",
    .style: "Style",
    .styleBlack: "Noir",
    .styleWhite: "Blanc",
    .styleBlur: "Flou",
    .opacity: "Opacité",
    .fadeSpeed: "Vitesse du fondu",
    .fadeInstant: "Instantané",
    .leaveDelay: "Délai de sortie",
    .leaveNone: "Aucun",
    .previewLabel: "Votre écran",
    .carePauseMediaTitle: "Mettre en pause quand une vidéo est à l'écran",
    .carePauseMediaSubtitle: "Plein écran, picture-in-picture, ou dans un onglet — toute vidéo visible. Les apps audio uniquement (musique, appels vocaux) ne mettent pas en pause.",
    .carePixelShiftTitle: "Décalage de pixels",
    .carePixelShiftSubtitle: "Décale subtilement le calque de ±1 pixel chaque minute pour que le cache de la barre des menus n'occupe pas toujours les mêmes pixels physiques.",
    .careBlackoutIdleTitle: "Écran noir sur les écrans protégés en cas d'inactivité",
    .careBlackoutIdleSubtitle: "Après une période sans saisie, couvre entièrement les écrans protégés.",
    .idleThreshold: "Seuil d'inactivité",
    .minute_1: "1 minute",
    .minutes_2: "2 minutes",
    .minutes_5: "5 minutes",
    .minutes_10: "10 minutes",
    .minutes_30: "30 minutes",
    .wakeDisplays: "Réveiller les écrans",
    .restDisplaysNow: "Mettre les écrans en repos",
    .scheduleTitle: "Repos automatique selon l'horaire",
    .scheduleSubtitle: "Forcer le repos des écrans protégés pendant les heures définies.",
    .scheduleFrom: "De",
    .scheduleTo: "à",
    .totalProtected: "Temps total protégé : %@",
    .unitHourMin: "%dh %dmin",
    .unitMin: "%dmin",
    .unitSec: "%ds",
    .menuPause: "Suspendre Display Flow",
    .menuResume: "Reprendre Display Flow",
    .menuPreferences: "Préférences…",
    .menuQuit: "Quitter Display Flow",
    .statusHibernating: "En veille",
    .subHibernateNoExternal: "Aucun écran externe connecté",
    .subHibernateBatterySaver: "Mode économie d'énergie activé",
    .subHibernateLowBattery: "Batterie inférieure à 50 %",
    .sectionPower: "Énergie",
    .careBatterySaverTitle: "Mode économie d'énergie",
    .careBatterySaverSubtitle: "Mettre tout en pause et libérer toutes les ressources.",
    .careAutoBatterySaverTitle: "Pause automatique sous 50 % de batterie",
    .careAutoBatterySaverSubtitle: "Arrête la surveillance lorsque vous êtes sur batterie et qu'elle baisse.",
    .powerNoExternalNote: "Se met toujours en pause quand aucun écran externe n'est connecté.",
    .careLaunchAtLoginTitle: "Ouvrir à l'ouverture de session",
    .careLaunchAtLoginSubtitle: "Lance Display Flow automatiquement quand vous vous connectez à votre Mac.",
    .applyAndClose: "Appliquer",
],

.de: [
    .appSubtitle: "Burn-in-Schutz für deinen Monitor",
    .statusPaused: "Pausiert",
    .statusNoDisplaysShort: "Keine Displays ausgewählt",
    .statusManualRest: "Displays ruhen",
    .statusScheduled: "Ruht nach Zeitplan",
    .statusMediaPaused: "Pausiert — Video wird abgespielt",
    .statusIdleBlackout: "Abgedunkelt — System inaktiv",
    .statusActiveOne: "Aktiv — schützt 1 Display",
    .statusActiveMany: "Aktiv — schützt %d Displays",
    .statusIdle: "Inaktiv — keine Displays ausgewählt",
    .subPaused: "Display Flow ist aus",
    .subNoDisplays: "Schalte unten ein Display ein",
    .subManualRest: "Klicke auf Aufwecken zum Fortsetzen",
    .subScheduled: "Auto-Ruhezeit ist aktiv",
    .subMediaPaused: "Setzt fort, wenn die Wiedergabe stoppt",
    .subIdleBlackout: "Wacht bei jeder Eingabe auf",
    .subActive: "Bewege den Cursor zwischen den Displays",
    .sectionDisplays: "Displays",
    .sectionAppearance: "Aussehen",
    .sectionCare: "Pflege",
    .sectionSchedule: "Zeitplan",
    .sectionLanguage: "Sprache",
    .noDisplaysDetected: "Keine Displays erkannt.",
    .badgeExternal: "EXTERN",
    .displayBuiltin: "Eingebaut",
    .displayExternal: "Extern",
    .displayProtected: "Geschützt",
    .displayNotProtected: "Nicht geschützt",
    .style: "Stil",
    .styleBlack: "Schwarz",
    .styleWhite: "Weiß",
    .styleBlur: "Unscharf",
    .opacity: "Deckkraft",
    .fadeSpeed: "Überblendgeschwindigkeit",
    .fadeInstant: "Sofort",
    .leaveDelay: "Verzögerung beim Verlassen",
    .leaveNone: "Keine",
    .previewLabel: "Dein Bildschirm",
    .carePauseMediaTitle: "Pausieren, wenn ein Video auf dem Bildschirm ist",
    .carePauseMediaSubtitle: "Vollbild, Picture-in-Picture oder in einem Tab — jedes sichtbare Video. Reine Audio-Apps (Musik, Sprachanrufe) pausieren das Abdunkeln nicht.",
    .carePixelShiftTitle: "Pixel-Verschiebung",
    .carePixelShiftSubtitle: "Verschiebt die Abdeckung minütlich um ±1 Pixel, damit die Menüleisten-Abdeckung nicht immer auf denselben physischen Pixeln liegt.",
    .careBlackoutIdleTitle: "Geschützte Displays bei Inaktivität abdunkeln",
    .careBlackoutIdleSubtitle: "Nach einer Phase ohne Eingabe geschützte Displays komplett abdecken.",
    .idleThreshold: "Inaktivitätsschwelle",
    .minute_1: "1 Minute",
    .minutes_2: "2 Minuten",
    .minutes_5: "5 Minuten",
    .minutes_10: "10 Minuten",
    .minutes_30: "30 Minuten",
    .wakeDisplays: "Displays aufwecken",
    .restDisplaysNow: "Displays jetzt ruhen lassen",
    .scheduleTitle: "Auto-Ruhe nach Zeitplan",
    .scheduleSubtitle: "Geschützte Displays während festgelegter Stunden ruhen lassen.",
    .scheduleFrom: "Von",
    .scheduleTo: "bis",
    .totalProtected: "Insgesamt geschützt: %@",
    .unitHourMin: "%dh %dm",
    .unitMin: "%dm",
    .unitSec: "%ds",
    .menuPause: "Display Flow pausieren",
    .menuResume: "Display Flow fortsetzen",
    .menuPreferences: "Einstellungen…",
    .menuQuit: "Display Flow beenden",
    .statusHibernating: "Im Ruhezustand",
    .subHibernateNoExternal: "Kein externer Bildschirm angeschlossen",
    .subHibernateBatterySaver: "Energiesparmodus aktiv",
    .subHibernateLowBattery: "Akku unter 50%",
    .sectionPower: "Energie",
    .careBatterySaverTitle: "Energiesparmodus",
    .careBatterySaverSubtitle: "Pausiert alles und gibt sämtliche Ressourcen frei.",
    .careAutoBatterySaverTitle: "Unter 50% Akku automatisch pausieren",
    .careAutoBatterySaverSubtitle: "Stoppt die Überwachung im Akkubetrieb bei niedrigem Stand.",
    .powerNoExternalNote: "Pausiert immer, wenn kein externer Bildschirm angeschlossen ist.",
    .careLaunchAtLoginTitle: "Beim Anmelden öffnen",
    .careLaunchAtLoginSubtitle: "Display Flow automatisch starten, wenn du dich an deinem Mac anmeldest.",
    .applyAndClose: "Übernehmen",
],

.it: [
    .appSubtitle: "Protezione dal burn-in per il tuo monitor",
    .statusPaused: "In pausa",
    .statusNoDisplaysShort: "Nessuno schermo selezionato",
    .statusManualRest: "Schermi a riposo",
    .statusScheduled: "A riposo secondo programma",
    .statusMediaPaused: "In pausa — è in riproduzione un video",
    .statusIdleBlackout: "Spento — sistema inattivo",
    .statusActiveOne: "Attivo — protegge 1 schermo",
    .statusActiveMany: "Attivo — protegge %d schermi",
    .statusIdle: "Inattivo — nessuno schermo selezionato",
    .subPaused: "Display Flow è spento",
    .subNoDisplays: "Attiva uno schermo sotto per iniziare",
    .subManualRest: "Premi Riattiva per riprendere",
    .subScheduled: "Finestra di riposo automatico attiva",
    .subMediaPaused: "Riprenderà alla fine della riproduzione",
    .subIdleBlackout: "Si riattiva con qualsiasi input",
    .subActive: "Sposta il cursore tra gli schermi",
    .sectionDisplays: "Schermi",
    .sectionAppearance: "Aspetto",
    .sectionCare: "Cura",
    .sectionSchedule: "Programmazione",
    .sectionLanguage: "Lingua",
    .noDisplaysDetected: "Nessuno schermo rilevato.",
    .badgeExternal: "ESTERNO",
    .displayBuiltin: "Integrato",
    .displayExternal: "Esterno",
    .displayProtected: "Protetto",
    .displayNotProtected: "Non protetto",
    .style: "Stile",
    .styleBlack: "Nero",
    .styleWhite: "Bianco",
    .styleBlur: "Sfocato",
    .opacity: "Opacità",
    .fadeSpeed: "Velocità dissolvenza",
    .fadeInstant: "Istantanea",
    .leaveDelay: "Ritardo all'uscita",
    .leaveNone: "Nessuno",
    .previewLabel: "Il tuo schermo",
    .carePauseMediaTitle: "Sospendi quando c'è un video sullo schermo",
    .carePauseMediaSubtitle: "Schermo intero, picture-in-picture o in una scheda — qualsiasi video visibile. Le app solo audio (musica, chiamate vocali) non sospendono l'oscuramento.",
    .carePixelShiftTitle: "Spostamento pixel",
    .carePixelShiftSubtitle: "Sposta la copertura ±1 pixel ogni minuto in modo che il copri-barra non resti sempre sugli stessi pixel fisici.",
    .careBlackoutIdleTitle: "Oscura schermi protetti durante l'inattività",
    .careBlackoutIdleSubtitle: "Dopo un periodo senza input, copre completamente gli schermi protetti.",
    .idleThreshold: "Soglia di inattività",
    .minute_1: "1 minuto",
    .minutes_2: "2 minuti",
    .minutes_5: "5 minuti",
    .minutes_10: "10 minuti",
    .minutes_30: "30 minuti",
    .wakeDisplays: "Riattiva schermi",
    .restDisplaysNow: "Metti schermi a riposo",
    .scheduleTitle: "Riposo automatico programmato",
    .scheduleSubtitle: "Forza il riposo degli schermi protetti durante gli orari impostati.",
    .scheduleFrom: "Da",
    .scheduleTo: "a",
    .totalProtected: "Tempo totale protetto: %@",
    .unitHourMin: "%dh %dm",
    .unitMin: "%dm",
    .unitSec: "%ds",
    .menuPause: "Sospendi Display Flow",
    .menuResume: "Riprendi Display Flow",
    .menuPreferences: "Preferenze…",
    .menuQuit: "Esci da Display Flow",
    .statusHibernating: "In ibernazione",
    .subHibernateNoExternal: "Nessun display esterno collegato",
    .subHibernateBatterySaver: "Modalità risparmio energetico attiva",
    .subHibernateLowBattery: "Batteria sotto il 50%",
    .sectionPower: "Energia",
    .careBatterySaverTitle: "Modalità risparmio energetico",
    .careBatterySaverSubtitle: "Mette tutto in pausa e libera le risorse.",
    .careAutoBatterySaverTitle: "Pausa automatica sotto il 50% di batteria",
    .careAutoBatterySaverSubtitle: "Interrompe il monitoraggio quando sei a batteria e sta calando.",
    .powerNoExternalNote: "Si mette sempre in pausa quando non c'è un display esterno collegato.",
    .careLaunchAtLoginTitle: "Apri all'accesso",
    .careLaunchAtLoginSubtitle: "Avvia Display Flow automaticamente quando accedi al tuo Mac.",
    .applyAndClose: "Applica",
],

.ja: [
    .appSubtitle: "モニターの焼き付き防止",
    .statusPaused: "一時停止中",
    .statusNoDisplaysShort: "ディスプレイが選択されていません",
    .statusManualRest: "ディスプレイ休止中",
    .statusScheduled: "スケジュールに従って休止中",
    .statusMediaPaused: "一時停止中 — 動画再生中",
    .statusIdleBlackout: "ブラックアウト — システム待機中",
    .statusActiveOne: "有効 — 1台のディスプレイを保護中",
    .statusActiveMany: "有効 — %d台のディスプレイを保護中",
    .statusIdle: "待機中 — ディスプレイが選択されていません",
    .subPaused: "Display Flow は無効です",
    .subNoDisplays: "下のディスプレイをオンにしてください",
    .subManualRest: "「ディスプレイを起こす」をクリックして再開",
    .subScheduled: "自動休止時間帯が有効です",
    .subMediaPaused: "再生終了後に再開します",
    .subIdleBlackout: "入力で復帰します",
    .subActive: "ディスプレイ間でカーソルを動かしてください",
    .sectionDisplays: "ディスプレイ",
    .sectionAppearance: "外観",
    .sectionCare: "ケア",
    .sectionSchedule: "スケジュール",
    .sectionLanguage: "言語",
    .noDisplaysDetected: "ディスプレイが検出されません。",
    .badgeExternal: "外部",
    .displayBuiltin: "内蔵",
    .displayExternal: "外部",
    .displayProtected: "保護中",
    .displayNotProtected: "未保護",
    .style: "スタイル",
    .styleBlack: "ブラック",
    .styleWhite: "ホワイト",
    .styleBlur: "ぼかし",
    .opacity: "不透明度",
    .fadeSpeed: "フェード速度",
    .fadeInstant: "即時",
    .leaveDelay: "離脱遅延",
    .leaveNone: "なし",
    .previewLabel: "あなたの画面",
    .carePauseMediaTitle: "画面に動画があるときは停止",
    .carePauseMediaSubtitle: "全画面、ピクチャ・イン・ピクチャ、タブ内 — 表示されているすべての動画。音声のみのアプリ(音楽、音声通話)は暗転を停止しません。",
    .carePixelShiftTitle: "ピクセルシフト",
    .carePixelShiftSubtitle: "1分ごとにオーバーレイを±1ピクセルずらして、メニューバーカバーが常に同じ物理ピクセルにあたらないようにします。",
    .careBlackoutIdleTitle: "待機中は保護ディスプレイをブラックアウト",
    .careBlackoutIdleSubtitle: "一定時間入力がないと保護ディスプレイを完全に覆います。",
    .idleThreshold: "待機しきい値",
    .minute_1: "1分",
    .minutes_2: "2分",
    .minutes_5: "5分",
    .minutes_10: "10分",
    .minutes_30: "30分",
    .wakeDisplays: "ディスプレイを起こす",
    .restDisplaysNow: "今すぐ休止",
    .scheduleTitle: "スケジュールで自動休止",
    .scheduleSubtitle: "設定した時間帯に保護ディスプレイを強制休止します。",
    .scheduleFrom: "開始",
    .scheduleTo: "終了",
    .totalProtected: "合計保護時間: %@",
    .unitHourMin: "%d時間 %d分",
    .unitMin: "%d分",
    .unitSec: "%d秒",
    .menuPause: "Display Flow を一時停止",
    .menuResume: "Display Flow を再開",
    .menuPreferences: "環境設定…",
    .menuQuit: "Display Flow を終了",
    .statusHibernating: "休止中",
    .subHibernateNoExternal: "外部ディスプレイが接続されていません",
    .subHibernateBatterySaver: "バッテリーセーバーモード",
    .subHibernateLowBattery: "バッテリー残量が 50% 未満です",
    .sectionPower: "電源",
    .careBatterySaverTitle: "バッテリーセーバーモード",
    .careBatterySaverSubtitle: "すべて一時停止し、リソースを解放します。",
    .careAutoBatterySaverTitle: "バッテリー 50% 未満で自動停止",
    .careAutoBatterySaverSubtitle: "バッテリー駆動で残量が少なくなったら監視を停止します。",
    .powerNoExternalNote: "外部ディスプレイが接続されていないときは常に一時停止します。",
    .careLaunchAtLoginTitle: "ログイン時に起動",
    .careLaunchAtLoginSubtitle: "Mac にサインインしたときに Display Flow を自動的に起動します。",
    .applyAndClose: "適用",
],

.zh: [
    .appSubtitle: "为您的显示器提供烧屏保护",
    .statusPaused: "已暂停",
    .statusNoDisplaysShort: "未选择任何显示器",
    .statusManualRest: "显示器休息中",
    .statusScheduled: "按计划休息中",
    .statusMediaPaused: "已暂停 — 正在播放视频",
    .statusIdleBlackout: "已黑屏 — 系统空闲",
    .statusActiveOne: "活跃 — 正在保护 1 台显示器",
    .statusActiveMany: "活跃 — 正在保护 %d 台显示器",
    .statusIdle: "空闲 — 未选择任何显示器",
    .subPaused: "Display Flow 已关闭",
    .subNoDisplays: "在下方启用显示器以开始",
    .subManualRest: "点击「唤醒显示器」以恢复",
    .subScheduled: "自动休息时段已激活",
    .subMediaPaused: "播放停止后将恢复",
    .subIdleBlackout: "任何输入即可唤醒",
    .subActive: "在显示器之间移动光标",
    .sectionDisplays: "显示器",
    .sectionAppearance: "外观",
    .sectionCare: "保护",
    .sectionSchedule: "计划",
    .sectionLanguage: "语言",
    .noDisplaysDetected: "未检测到显示器。",
    .badgeExternal: "外接",
    .displayBuiltin: "内置",
    .displayExternal: "外接",
    .displayProtected: "已保护",
    .displayNotProtected: "未保护",
    .style: "样式",
    .styleBlack: "黑色",
    .styleWhite: "白色",
    .styleBlur: "模糊",
    .opacity: "不透明度",
    .fadeSpeed: "淡入淡出速度",
    .fadeInstant: "立即",
    .leaveDelay: "离开延迟",
    .leaveNone: "无",
    .previewLabel: "您的屏幕",
    .carePauseMediaTitle: "屏幕上有视频时暂停",
    .carePauseMediaSubtitle: "全屏、画中画或标签页中 — 任何可见视频。仅音频应用(音乐、语音通话)不会暂停变暗。",
    .carePixelShiftTitle: "像素位移",
    .carePixelShiftSubtitle: "每分钟将遮罩偏移 ±1 像素,使菜单栏遮挡不会始终落在相同的物理像素上。",
    .careBlackoutIdleTitle: "空闲时遮挡保护的显示器",
    .careBlackoutIdleSubtitle: "一段时间无输入后,完全遮挡受保护的显示器。",
    .idleThreshold: "空闲阈值",
    .minute_1: "1 分钟",
    .minutes_2: "2 分钟",
    .minutes_5: "5 分钟",
    .minutes_10: "10 分钟",
    .minutes_30: "30 分钟",
    .wakeDisplays: "唤醒显示器",
    .restDisplaysNow: "立即休息显示器",
    .scheduleTitle: "按计划自动休息",
    .scheduleSubtitle: "在设定的时段强制让受保护的显示器休息。",
    .scheduleFrom: "从",
    .scheduleTo: "至",
    .totalProtected: "总保护时间:%@",
    .unitHourMin: "%d 小时 %d 分钟",
    .unitMin: "%d 分钟",
    .unitSec: "%d 秒",
    .menuPause: "暂停 Display Flow",
    .menuResume: "恢复 Display Flow",
    .menuPreferences: "偏好设置…",
    .menuQuit: "退出 Display Flow",
    .statusHibernating: "已休眠",
    .subHibernateNoExternal: "未连接外接显示器",
    .subHibernateBatterySaver: "省电模式已开启",
    .subHibernateLowBattery: "电量低于 50%",
    .sectionPower: "电源",
    .careBatterySaverTitle: "省电模式",
    .careBatterySaverSubtitle: "暂停所有功能并释放系统资源。",
    .careAutoBatterySaverTitle: "电量低于 50% 时自动暂停",
    .careAutoBatterySaverSubtitle: "在使用电池且电量较低时停止监测。",
    .powerNoExternalNote: "未连接外接显示器时始终暂停。",
    .careLaunchAtLoginTitle: "登录时启动",
    .careLaunchAtLoginSubtitle: "登录 Mac 时自动启动 Display Flow。",
    .applyAndClose: "应用",
],

.ko: [
    .appSubtitle: "모니터의 번인 방지",
    .statusPaused: "일시 중지됨",
    .statusNoDisplaysShort: "선택된 디스플레이가 없습니다",
    .statusManualRest: "디스플레이 휴식 중",
    .statusScheduled: "예약된 휴식 중",
    .statusMediaPaused: "일시 중지됨 — 동영상 재생 중",
    .statusIdleBlackout: "암전 — 시스템 대기 중",
    .statusActiveOne: "활성화 — 1개의 디스플레이 보호 중",
    .statusActiveMany: "활성화 — %d개의 디스플레이 보호 중",
    .statusIdle: "대기 — 선택된 디스플레이 없음",
    .subPaused: "Display Flow가 꺼져 있습니다",
    .subNoDisplays: "아래 디스플레이를 켜서 시작하세요",
    .subManualRest: "디스플레이 깨우기를 클릭하여 재개",
    .subScheduled: "자동 휴식 시간대가 활성화되었습니다",
    .subMediaPaused: "재생이 멈추면 재개됩니다",
    .subIdleBlackout: "입력 시 깨어납니다",
    .subActive: "디스플레이 사이로 커서를 이동하세요",
    .sectionDisplays: "디스플레이",
    .sectionAppearance: "모양",
    .sectionCare: "관리",
    .sectionSchedule: "일정",
    .sectionLanguage: "언어",
    .noDisplaysDetected: "디스플레이가 감지되지 않았습니다.",
    .badgeExternal: "외부",
    .displayBuiltin: "내장",
    .displayExternal: "외부",
    .displayProtected: "보호됨",
    .displayNotProtected: "보호되지 않음",
    .style: "스타일",
    .styleBlack: "검정",
    .styleWhite: "흰색",
    .styleBlur: "흐림",
    .opacity: "불투명도",
    .fadeSpeed: "페이드 속도",
    .fadeInstant: "즉시",
    .leaveDelay: "벗어남 지연",
    .leaveNone: "없음",
    .previewLabel: "당신의 화면",
    .carePauseMediaTitle: "화면에 동영상이 있을 때 일시 중지",
    .carePauseMediaSubtitle: "전체화면, PIP, 탭 안 — 보이는 모든 동영상. 오디오 전용 앱(음악, 음성 통화)은 어두워짐을 멈추지 않습니다.",
    .carePixelShiftTitle: "픽셀 이동",
    .carePixelShiftSubtitle: "1분마다 ±1 픽셀씩 오버레이를 미세하게 옮겨 메뉴 바 커버가 항상 같은 물리 픽셀 위에 놓이지 않게 합니다.",
    .careBlackoutIdleTitle: "대기 중 보호된 디스플레이 암전",
    .careBlackoutIdleSubtitle: "입력이 없는 시간 후 보호된 디스플레이를 완전히 가립니다.",
    .idleThreshold: "대기 임계값",
    .minute_1: "1분",
    .minutes_2: "2분",
    .minutes_5: "5분",
    .minutes_10: "10분",
    .minutes_30: "30분",
    .wakeDisplays: "디스플레이 깨우기",
    .restDisplaysNow: "지금 디스플레이 휴식",
    .scheduleTitle: "일정에 따라 자동 휴식",
    .scheduleSubtitle: "지정된 시간 동안 보호된 디스플레이를 강제 휴식시킵니다.",
    .scheduleFrom: "시작",
    .scheduleTo: "끝",
    .totalProtected: "총 보호 시간: %@",
    .unitHourMin: "%d시간 %d분",
    .unitMin: "%d분",
    .unitSec: "%d초",
    .menuPause: "Display Flow 일시 중지",
    .menuResume: "Display Flow 재개",
    .menuPreferences: "환경설정…",
    .menuQuit: "Display Flow 종료",
    .statusHibernating: "절전 중",
    .subHibernateNoExternal: "외부 디스플레이가 연결되지 않았습니다",
    .subHibernateBatterySaver: "배터리 절약 모드가 켜져 있습니다",
    .subHibernateLowBattery: "배터리가 50% 미만입니다",
    .sectionPower: "전원",
    .careBatterySaverTitle: "배터리 절약 모드",
    .careBatterySaverSubtitle: "모든 기능을 일시 중지하고 리소스를 해제합니다.",
    .careAutoBatterySaverTitle: "배터리 50% 미만에서 자동 중지",
    .careAutoBatterySaverSubtitle: "배터리 사용 중이고 잔량이 낮을 때 모니터링을 중지합니다.",
    .powerNoExternalNote: "외부 디스플레이가 없으면 항상 일시 중지됩니다.",
    .careLaunchAtLoginTitle: "로그인 시 실행",
    .careLaunchAtLoginSubtitle: "Mac에 로그인하면 Display Flow를 자동으로 시작합니다.",
    .applyAndClose: "적용",
],

]

func translate(_ key: LocKey, language: AppLanguage) -> String {
    return strings[language]?[key]
        ?? strings[.en]?[key]
        ?? key.rawValue
}
